-- AlterTable
ALTER TABLE "MeterPeriod" ADD COLUMN     "dateCreated" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "dateModified" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
